import re


ABSTRACTIONS = [
  (
    re.compile(r' '),
    'ABS-SINGLE-SPACE'
  ),
  (
    re.compile(r'  '),
    'ABS-DOUBLE-SPACE'
  ),
  (
    re.compile(r'\n'),
    'ABS-NEW-LINE'
  ),
  (
    re.compile(r'\t'),
    'ABS-TAB'
  ),
  (
    re.compile(r'http://'),
    'ABS-URL-PROTOCOL-HTTP'
  ),
  (
    re.compile(r'https://'),
    'ABS-URL-PROTOCOL-HTTPS'
  ),
  (
    re.compile(r'ftp://'),
    'ABS-URL-PROTOCOL-FTP'
  ),
  (
    re.compile(r'git://'),
    'ABS-URL-PROTOCOL-GIT'
  ),
  (
    re.compile(
      r'(?i)\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9.\-]+[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)/)(?:[^\s()<>{}\[\]]+|\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\))+(?:\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’])|(?:(?<!@)[a-z0-9]+(?:[.\-][a-z0-9]+)*[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)\b/?(?!@)))'
    ),
    'ABS-PROBABLY-URL'
  ),
  (
    re.compile(
      r'--no-document|--no-rdoc'
    ),
    'ABS-CONFIG-NO-DOCUMENT'
  ),
  (
    re.compile(
      r'(^([a-z]|[A-Z]):(?=\\(?![\0-\37<>:"/\\|?*])|\/(?![\0-\37<>:"/\\|?*])|$)|^\\(?=[\\\/][^\0-\37<>:"/\\|?*]+)|^(?=(\\|\/)$)|^\.(?=(\\|\/)$)|^\.\.(?=(\\|\/)$)|^(?=(\\|\/)[^\0-\37<>:"/\\|?*]+)|^\.(?=(\\|\/)[^\0-\37<>:"/\\|?*]+)|^\.\.(?=(\\|\/)[^\0-\37<>:"/\\|?*]+))((\\|\/)[^\0-\37<>:"/\\|?*]+|(\\|\/)$)*()$'
    ),
    'ABS-MAYBE-PATH'
  ),
  (
    re.compile(
      r'^\/$|(^(?=\/)|^\.|^\.\.)(\/(?=[^/\0])[^/\0]+)*\/?$'
    ),
    'ABS-MAYBE-PATH'
  ),
  (
    re.compile(r'/build|build/'),
    'ABS-MAYBE-BUILD-DIR'
  ),
  (
    re.compile(r'var/cache/yum'),
    'ABS-VAR-CACHE-YUM'
  ),
  (
    re.compile(r'/src|src/'),
    'ABS-MAYBE-SRC-DIR'
  ),
  (
    re.compile(r'/usr/src'),
    'ABS-USR-SRC-DIR'
  ),
  (
    re.compile(r'/\.cache'),
    'ABS-PATH-DOT-CACHE'
  ),
  (
    re.compile(r'/\.gem'),
    'ABS-PATH-DOT-GEM'
  ),
  (
    re.compile(r'\.asc'),
    'ABS-EXTENSION-ASC'
  ),
  (
    re.compile(r'\.tar'),
    'ABS-EXTENSION-TAR'
  ),
  (
    re.compile(r'/root'),
    'ABS-PATH-ROOT-DIR'
  ),
  (
    re.compile(r'pool\.'),
    'ABS-URL-POOL'
  ),
  (
    re.compile(r'ha\.pool\.'),
    'ABS-URL-HA-POOL'
  ),
  (
    re.compile(r'^/'),
    'ABS-PATH-ABSOLUTE'
  ),
  (
    re.compile(r'^(\.)+/'),
    'ABS-PATH-RELATIVE'
  ),
  (
    re.compile(r'^~'),
    'ABS-PATH-HOME'
  ),
  (
    re.compile(r'/var'),
    'ABS-PATH-VAR'
  ),
  (
    re.compile(r'^\*$'),
    'ABS-GLOB-STAR'
  ),
  (
    re.compile(r'apt/lists'),
    'ABS-APT-LISTS'
  ),
  (
    re.compile(r'(t|T)rue'),
    'ABS-TRUE'
  ),
  (
    re.compile(r'(t|F)rue'),
    'ABS-FALSE'
  )
]
